# Java Version
export JAVA_HOME=$(/usr/libexec/java_home)

HISTFILE=~/.histfile
SAVEHIST=10000
setopt autocd extendedglob
unsetopt beep
bindkey -v

# The following lines were added by compinstall
zstyle :compinstall filename '/home/adam/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# completion
autoload -U compinit && compinit

#for function in ~/.zsh/functions/*; do
#  source $function
#done

# automatically enter directories without cd
setopt auto_cd

# use vim as the visual editor
export VISUAL=vim
export EDITOR=$VISUAL

# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# emacs mode
bindkey -e

# use incremental search
bindkey "^R" history-incremental-search-backward

# add some readline keys back
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

# handy keybindings
bindkey "^P" history-search-backward
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word
bindkey -s "^T" "^[Isudo ^[A" # "t" for "toughguy"

# setup
autoload colors; colors;
export LSCOLORS="Gxfxcxdxbxegedabagacad"
setopt prompt_subst

# ignore duplicate history entries
setopt histignoredups

# keep TONS of history
export HISTSIZE=4096

# automatically pushd
setopt auto_pushd
export dirstacksize=5

# awesome cd movements from zshkit
#setopt AUTOCD
#setopt AUTOPUSHD PUSHDMINUS PUSHDSILENT PUSHDTOHOME
#setopt cdablevars

# Enable extended globbing
setopt EXTENDED_GLOB
alias to=". jumpto"

if type compdef >/dev/null; then
   compdef hub=git
fi

### Prompt
source ~/.zsh/git-prompt/zshrc.sh
echo $(git_super_status)
PROMPT='%B%~%b$(git_super_status) '
